### ISSUE TITLE
功能添加意见

### ISSUE THREAD

**Issue by zxc173123** [Ostwind23/MAA-for-Millennium-Tour#13]
日常能不能加上列阵材料扫荡，公会点赞，神谕司换人和休息，赛马，那个钓鱼功能好像无效。

**Comment by Ostwind23** [comment]
神谕司换人的功能是已经有的; 赛马我还没体验过, 到时候看看; 阵列材料扫荡是什么意思？ 钓鱼功能是怎么个无效法？我需要更多信息, 哪个钓鱼无效, 卡在那里之类的。

**Comment by zxc173123** [comment]
阵列材料
![QQ截图20241027075729](https://github.com/user-attachments/assets/bc906490-2c08-430d-a487-126423aa38b1)
公会点赞
![QQ截图20241027075905](https://github.com/user-attachments/assets/9dc8b00c-b753-4883-a2d4-2022fc0e079e)

**Comment by zxc173123** [comment]
自动识别钓鱼，它点到神谕司就不动然后显示完成任务
![QQ截图20241027080046](https://github.com/user-attachments/assets/838698ee-f329-4ce5-94e5-8120875f2b2a)
钓台入口自动钓鱼，手动进到钓鱼场才会启动一次钓鱼竿然后就不动再然后就显示完成任务了
![QQ截图20241027080652](https://github.com/user-attachments/assets/3f946b28-293c-4039-9737-f0f85560544c)

**Comment by zxc173123** [comment]
神谕司换人和休息的判定是什么，是启动就换人和休息吗？
我开了几次脚本都没换人和休息。

**Comment by Ostwind23** [comment]
> 神谕司换人和休息的判定是什么，是启动就换人和休息吗？ 我开了几次脚本都没换人和休息。

就是在神谕司收完奖励后就自动换人的, 如果显示疲劳了就换, 没显示疲劳就没换。

**Comment by Ostwind23** [comment]
> 自动识别钓鱼，它点到神谕司就不动然后显示完成任务 ![QQ截图20241027080046](https://private-user-images.githubusercontent.com/56154254/380459205-838698ee-f329-4ce5-94e5-8120875f2b2a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDkxODcsIm5iZiI6MTczMDAwODg4NywicGF0aCI6Ii81NjE1NDI1NC8zODA0NTkyMDUtODM4Njk4ZWUtZjMyOS00Y2U1LTk0ZTUtODEyMDg3NWYyYjJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA2MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMGFmNmEzNzVhMGZjMGJjYmYwNWNhM2VhYzg0MDdhZWEyNTE5NmRkMTNmODliMGVkYmRhYzI2NjZiN2VhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NCX7QrzLlZhQhx7wCJmAxlpbEZ36CqRIgghQy3TlKrk) 钓台入口自动钓鱼，手动进到钓鱼场才会启动一次钓鱼竿然后就不动再然后就显示完成任务了 ![QQ截图20241027080652](https://private-user-images.githubusercontent.com/56154254/380459347-3f946b28-293c-4039-9737-f0f85560544c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDkxODcsIm5iZiI6MTczMDAwODg4NywicGF0aCI6Ii81NjE1NDI1NC8zODA0NTkzNDctM2Y5NDZiMjgtMjkzYy00MDM5LTk3MzctZjBmODU1NjA1NDRjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA2MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYzdkMGVjMDZkNDcyMTE4NzllZWIxZTBjODE2NWMwMmNmNDE0NGY1ODZkN2FkOWJiZjY5NzM1ZmYzMmM5ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DxCCgm830dkZoaGEKfurzPU7zIK1lr3oknBxtvmqdw8)

从主界面进入的自动识别钓鱼这里, 可能是模版匹配的问题, 我晚点弄完手头的活看看ps抠抠图提升一下准确率;
钓台入口的自动钓鱼和主界面进入的自动钓鱼一样, 我写了都是只能适配那种钓鱼面板已经达到不操作就能把鱼钓上来的人, 你这线已经断了, 出于节省鱼饵的考虑我没加断线后再钓的设定。 如果面板太低就用文件夹里附带的那个Autofishing.exe（这个目前应该也有点问题, 之前体积太大了我选择了在工作流里构建, 但是容易出现路径问题, 发版不稳定。我后面看看能不能让用户自己用脚本在本机上一键安装）, 那个是加了根据鱼移动的方向去拖鱼竿的功能, 面板低的也能用。由于这个程序是maa2.0之前写的, 那会外部的程序还没法接进maa里, 所以就只能这样子另外编译。后面等弄完考研和毕业论文那些东西后我再看着整合重构吧。

**Comment by zxc173123** [comment]
> > 自动识别钓鱼，它点到神谕司就不动然后显示完成任务 ![QQ截图20241027080046](https://private-user-images.githubusercontent.com/56154254/380459205-838698ee-f329-4ce5-94e5-8120875f2b2a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDkxODcsIm5iZiI6MTczMDAwODg4NywicGF0aCI6Ii81NjE1NDI1NC8zODA0NTkyMDUtODM4Njk4ZWUtZjMyOS00Y2U1LTk0ZTUtODEyMDg3NWYyYjJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA2MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMGFmNmEzNzVhMGZjMGJjYmYwNWNhM2VhYzg0MDdhZWEyNTE5NmRkMTNmODliMGVkYmRhYzI2NjZiN2VhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NCX7QrzLlZhQhx7wCJmAxlpbEZ36CqRIgghQy3TlKrk) 钓台入口自动钓鱼，手动进到钓鱼场才会启动一次钓鱼竿然后就不动再然后就显示完成任务了 ![QQ截图20241027080652](https://private-user-images.githubusercontent.com/56154254/380459347-3f946b28-293c-4039-9737-f0f85560544c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDkxODcsIm5iZiI6MTczMDAwODg4NywicGF0aCI6Ii81NjE1NDI1NC8zODA0NTkzNDctM2Y5NDZiMjgtMjkzYy00MDM5LTk3MzctZjBmODU1NjA1NDRjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA2MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYzdkMGVjMDZkNDcyMTE4NzllZWIxZTBjODE2NWMwMmNmNDE0NGY1ODZkN2FkOWJiZjY5NzM1ZmYzMmM5ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DxCCgm830dkZoaGEKfurzPU7zIK1lr3oknBxtvmqdw8)
> 
> 从主界面进入的自动识别钓鱼这里, 可能是模版匹配的问题, 我晚点弄完手头的活看看ps抠抠图提升一下准确率; 钓台入口的自动钓鱼和主界面进入的自动钓鱼一样, 我写了都是只能适配那种钓鱼面板已经达到不操作就能把鱼钓上来的人, 你这线已经断了, 出于节省鱼饵的考虑我没加断线后再钓的设定。 如果面板太低就用文件夹里附带的那个Autofishing.exe（这个目前应该也有点问题, 之前体积太大了我选择了在工作流里构建, 但是容易出现路径问题, 发版不稳定。我后面看看能不能让用户自己用脚本在本机上一键安装）, 那个是加了根据鱼移动的方向去拖鱼竿的功能, 面板低的也能用。由于这个程序是maa2.0之前写的, 那会外部的程序还没法接进maa里, 所以就只能这样子另外编译。后面等弄完考研和毕业论文那些东西后我再看着整合重构吧。

话说你有Q群吗在贴吧和github交流不太方便啊

**Comment by Ostwind23** [comment]
> > > 自动识别钓鱼，它点到神谕司就不动然后显示完成任务 ![QQ截图20241027080046](https://private-user-images.githubusercontent.com/56154254/380459205-838698ee-f329-4ce5-94e5-8120875f2b2a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDkxODcsIm5iZiI6MTczMDAwODg4NywicGF0aCI6Ii81NjE1NDI1NC8zODA0NTkyMDUtODM4Njk4ZWUtZjMyOS00Y2U1LTk0ZTUtODEyMDg3NWYyYjJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA2MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMGFmNmEzNzVhMGZjMGJjYmYwNWNhM2VhYzg0MDdhZWEyNTE5NmRkMTNmODliMGVkYmRhYzI2NjZiN2VhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NCX7QrzLlZhQhx7wCJmAxlpbEZ36CqRIgghQy3TlKrk) 钓台入口自动钓鱼，手动进到钓鱼场才会启动一次钓鱼竿然后就不动再然后就显示完成任务了 ![QQ截图20241027080652](https://private-user-images.githubusercontent.com/56154254/380459347-3f946b28-293c-4039-9737-f0f85560544c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDkxODcsIm5iZiI6MTczMDAwODg4NywicGF0aCI6Ii81NjE1NDI1NC8zODA0NTkzNDctM2Y5NDZiMjgtMjkzYy00MDM5LTk3MzctZjBmODU1NjA1NDRjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDA2MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYzdkMGVjMDZkNDcyMTE4NzllZWIxZTBjODE2NWMwMmNmNDE0NGY1ODZkN2FkOWJiZjY5NzM1ZmYzMmM5ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DxCCgm830dkZoaGEKfurzPU7zIK1lr3oknBxtvmqdw8)
> > 
> > 
> > 从主界面进入的自动识别钓鱼这里, 可能是模版匹配的问题, 我晚点弄完手头的活看看ps抠抠图提升一下准确率; 钓台入口的自动钓鱼和主界面进入的自动钓鱼一样, 我写了都是只能适配那种钓鱼面板已经达到不操作就能把鱼钓上来的人, 你这线已经断了, 出于节省鱼饵的考虑我没加断线后再钓的设定。 如果面板太低就用文件夹里附带的那个Autofishing.exe（这个目前应该也有点问题, 之前体积太大了我选择了在工作流里构建, 但是容易出现路径问题, 发版不稳定。我后面看看能不能让用户自己用脚本在本机上一键安装）, 那个是加了根据鱼移动的方向去拖鱼竿的功能, 面板低的也能用。由于这个程序是maa2.0之前写的, 那会外部的程序还没法接进maa里, 所以就只能这样子另外编译。后面等弄完考研和毕业论文那些东西后我再看着整合重构吧。
> 
> 话说你有Q群吗在贴吧和github交流不太方便啊

没, 贴吧也就200来人点赞, git这里50个star, 我也不想开群, 主要认识的人也不多, 到时候管理啥的又麻烦。直接用邮箱和我交流吧, readme那里有写我的邮箱, 而且邮箱发文件啥的也方便, 我这边也好及时收到。
